/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Audio.
 *
 * Ghoti.io Audio is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Audio is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file
 *
 * Opening an Opus stream: the two headers, the tags, and the length.
 *
 * **The length is the last page's granule position minus the pre-skip**,
 * and both halves of that are load-bearing. Opus states no sample count
 * either, so the granule position is the only answer - and unlike Vorbis
 * it also begins with samples the recording does not contain, which the
 * granule positions count and `OpusHead` states the number of. A reader
 * that took the position verbatim reports every file a few milliseconds
 * long; one that forgot the position entirely has nothing at all.
 */

#include "../../container/ogg/ogg.h"
#include "../../core/meta_internal.h"
#include "../../meta/scheme.h"
#include "../shared/bytes.h"
#include "opus_internal.h"
#include <ghoti.io/cutil/allocator.h>
#include <string.h>

static void note(GAUD_Diagnostics * diagnostics, uint64_t offset,
    GAUD_Diag_Severity severity, const char * message) {
  if (!diagnostics) {
    return;
  }
  GAUD_Diagnostic entry = {
      .codec_name = "opus",
      .offset = offset,
      .element_id = 0,
      .severity = severity,
      .recommended_action = message,
  };
  (void)gaud_diagnostics_append(diagnostics, &entry);
}

GAUD_Result gaud_opus_parse_head(
    const unsigned char * data, size_t size, OPUS_Head * out) {
  if (size < OPUS_MAGIC_SIZE
      || memcmp(data, OPUS_HEAD_MAGIC, OPUS_MAGIC_SIZE) != 0) {
    return GAUD_ERR_FORMAT;
  }
  if (size < OPUS_HEAD_MIN) {
    return GAUD_ERR_CORRUPT;
  }
  memset(out, 0, sizeof(*out));
  out->version = data[8];
  out->channels = data[9];
  out->pre_skip = gaud_rd_u16le(data + 10);
  out->input_rate = gaud_rd_u32le(data + 12);
  out->output_gain = (int16_t)gaud_rd_u16le(data + 16);
  out->mapping_family = data[18];

  /*
   * **The major version is the top four bits**, and that is the one
   * field here where a plain comparison is wrong. RFC 7845 splits the
   * byte: a decoder must refuse a major version it does not know and
   * must *accept* any minor version, because a minor bump only ever
   * appends fields. Treating the byte as a whole number refuses every
   * future minor revision of a format that promised they would work.
   */
  if ((out->version >> 4) != 0) {
    return GAUD_ERR_UNSUPPORTED;
  }
  if (out->channels == 0) {
    return GAUD_ERR_CORRUPT;
  }

  if (out->mapping_family == 0) {
    /* One or two channels, one stream, coupled if there are two. */
    if (out->channels > 2u) {
      return GAUD_ERR_CORRUPT;
    }
    out->streams = 1;
    out->coupled = out->channels - 1u;
    for (uint32_t i = 0; i < out->channels; ++i) {
      out->mapping[i] = (unsigned char)i;
    }
    return GAUD_OK;
  }
  if (out->mapping_family != 1u && out->mapping_family != 255u) {
    /* 2 to 254 are reserved. A stream using one states a channel
     * mapping this cannot interpret, and guessing at speaker positions
     * is worse than declining. */
    return GAUD_ERR_UNSUPPORTED;
  }
  if (out->mapping_family == 1u && out->channels > 8u) {
    return GAUD_ERR_CORRUPT; /* Family 1 is the Vorbis orders, up to 8. */
  }
  if (size < OPUS_HEAD_MIN + 2u + out->channels) {
    return GAUD_ERR_CORRUPT;
  }
  out->streams = data[19];
  out->coupled = data[20];
  if (out->streams == 0 || out->coupled > out->streams
      || out->streams + out->coupled > 255u) {
    return GAUD_ERR_CORRUPT;
  }
  for (uint32_t i = 0; i < out->channels; ++i) {
    unsigned char which = data[21 + i];
    /* 255 means "this channel is silent", which is legal. Anything else
     * names a decoded channel, and a number past the end of what the
     * streams produce is a stream this refuses rather than an index to
     * follow. */
    if (which != 255u && which >= out->streams + out->coupled) {
      return GAUD_ERR_CORRUPT;
    }
    out->mapping[i] = which;
  }
  return GAUD_OK;
}

/**
 * The frame size in 48 kHz samples for each of the 32 configurations.
 *
 * **Generated by nothing and typed here, because it is 32 numbers in a
 * pattern the RFC states as prose rather than as a table.** Configs 0 to
 * 11 are SILK at 10, 20, 40 and 60 ms for each of three bandwidths; 12
 * to 15 are hybrid at 10 and 20 ms for two; 16 to 31 are CELT at 2.5, 5,
 * 10 and 20 ms for four. The arithmetic below reconstructs each from its
 * index rather than listing them, so there is nothing to mistype - and
 * the unit tests check every one of the 32 against the durations the RFC
 * names.
 */
static uint32_t config_frame_size(unsigned config, OPUS_Mode * out_mode,
    unsigned * out_bandwidth) {
  if (config < 12u) {
    *out_mode = OPUS_MODE_SILK;
    *out_bandwidth = config / 4u; /* narrow, medium, wide */
    /* 10, 20, 40, 60 ms. */
    static const uint32_t silk[4] = {480u, 960u, 1920u, 2880u};
    return silk[config % 4u];
  }
  if (config < 16u) {
    *out_mode = OPUS_MODE_HYBRID;
    *out_bandwidth = 3u + (config - 12u) / 2u; /* super-wide, full */
    /* 10 and 20 ms. */
    return (config % 2u) ? 960u : 480u;
  }
  *out_mode = OPUS_MODE_CELT;
  *out_bandwidth = (config - 16u) / 4u;
  if (*out_bandwidth == 1u) {
    *out_bandwidth = 2u; /* CELT skips medium band: narrow, wide, ... */
  }
  else if (*out_bandwidth >= 2u) {
    *out_bandwidth += 1u;
  }
  /* 2.5, 5, 10, 20 ms. */
  static const uint32_t celt[4] = {120u, 240u, 480u, 960u};
  return celt[(config - 16u) % 4u];
}

GAUD_Result gaud_opus_parse_toc(
    const unsigned char * data, size_t size, OPUS_Toc * out) {
  if (size < 1u) {
    return GAUD_ERR_CORRUPT;
  }
  memset(out, 0, sizeof(*out));
  unsigned config = (unsigned)(data[0] >> 3);
  out->stereo = (data[0] & 0x04u) != 0;
  out->code = (unsigned)(data[0] & 0x03u);
  out->frame_size = config_frame_size(config, &out->mode, &out->bandwidth);

  switch (out->code) {
  case 0:
    out->frames = 1;
    break;
  case 1:
    /* Two frames of equal size; the remaining bytes must divide in two. */
    if ((size - 1u) % 2u != 0) {
      return GAUD_ERR_CORRUPT;
    }
    out->frames = 2;
    break;
  case 2:
    /* Two frames, the first's length stated. One or two bytes of it. */
    if (size < 2u) {
      return GAUD_ERR_CORRUPT;
    }
    {
      size_t at = 1;
      uint32_t first = data[at++];
      if (first >= 252u) {
        if (at >= size) {
          return GAUD_ERR_CORRUPT;
        }
        first += (uint32_t)data[at++] * 4u;
      }
      if (at + first > size) {
        return GAUD_ERR_CORRUPT;
      }
    }
    out->frames = 2;
    break;
  default:
    /*
     * The arbitrary framing: a count, a flag for variable bit rate, a
     * flag for padding, and then either a length per frame or nothing
     * at all. The count is the low six bits and **zero is not legal** -
     * a packet of no frames would advance a stream by nothing and is
     * how a decoder is made to loop.
     */
    if (size < 2u) {
      return GAUD_ERR_CORRUPT;
    }
    out->frames = (uint32_t)(data[1] & 0x3Fu);
    if (out->frames == 0) {
      return GAUD_ERR_CORRUPT;
    }
    /* And a packet may not exceed 120 ms, which bounds the count by the
     * frame size: 48 frames of 2.5 ms, 6 of 20 ms, 2 of 60 ms. */
    if ((uint64_t)out->frames * out->frame_size > 5760u) {
      return GAUD_ERR_CORRUPT;
    }
    break;
  }
  return GAUD_OK;
}

/** How many 48 kHz samples a packet is worth, or 0 if it is not one. */
static uint32_t packet_samples(const unsigned char * data, size_t size) {
  OPUS_Toc toc;
  if (gaud_opus_parse_toc(data, size, &toc) != GAUD_OK) {
    return 0;
  }
  return toc.frames * toc.frame_size;
}

/** Read the two header packets, taking the tags out of the second. */
static GAUD_Result read_headers(OGG_Reader * reader, OPUS_File * state,
    const GAUD_Limits * limits, GAUD_Meta * meta,
    GAUD_Diagnostics * diagnostics) {
  const unsigned char * packet = NULL;
  size_t size = 0;
  GAUD_Result result
      = gaud_ogg_reader_packet(reader, &packet, &size, NULL, NULL);
  if (result != GAUD_OK) {
    return result == GAUD_ERR_FORMAT ? GAUD_ERR_CORRUPT : result;
  }
  result = gaud_opus_parse_head(packet, size, &state->head);
  if (result != GAUD_OK) {
    return result;
  }

  result = gaud_ogg_reader_packet(reader, &packet, &size, NULL, NULL);
  if (result != GAUD_OK) {
    return result == GAUD_ERR_FORMAT ? GAUD_ERR_CORRUPT : result;
  }
  if (size < OPUS_MAGIC_SIZE
      || memcmp(packet, OPUS_TAGS_MAGIC, OPUS_MAGIC_SIZE) != 0) {
    return GAUD_ERR_CORRUPT;
  }
  if (size - OPUS_MAGIC_SIZE > limits->max_metadata_bytes) {
    return GAUD_ERR_LIMIT;
  }
  /*
   * A Vorbis comment block, and **without the framing bit Vorbis's own
   * comment header ends with**. RFC 7845 drops it, which costs nothing
   * here because src/meta/vorbis_comment.c stops where the comment list
   * ends rather than at the end of its buffer - the same property that
   * lets the Vorbis reader hand it a buffer with the bit still on.
   */
  return gaud_vorbis_comment_parse(packet + OPUS_MAGIC_SIZE,
      size - OPUS_MAGIC_SIZE, limits, meta, diagnostics);
}

GAUD_Result gaud_opus_open(const GAUD_Codec * codec, GAUD_Stream * stream,
    const GAUD_Limits * limits, GAUD_Diagnostics * diagnostics,
    GAUD_Doc ** out_doc) {
  if (!stream || !limits || !out_doc) {
    return GAUD_ERR_INVALID;
  }
  if (!gaud_stream_seekable(stream)) {
    note(diagnostics, 0, GAUD_DIAG_ERROR,
        "an Opus stream can only be opened from a seekable stream, "
        "because its length is stated only by its last page");
    return GAUD_ERR_UNSUPPORTED;
  }

  const GAUD_Allocator * allocator = gaud_stream_allocator(stream);
  GAUD_Meta * meta = NULL;
  GAUD_Result result = gaud_meta_create(allocator, &meta);
  if (result != GAUD_OK) {
    return result;
  }

  OPUS_File * state = NULL;
  GAUD_Doc * doc = NULL;
  GAUD_Result failure = GAUD_OK;
  OGG_Reader reader;
  gaud_ogg_reader_init(&reader, stream, allocator);

  state = gcu_allocator_malloc(allocator, sizeof(*state));
  if (!state) {
    failure = GAUD_ERR_OOM;
    goto Fail;
  }
  memset(state, 0, sizeof(*state));
  state->allocator = allocator;

  result = read_headers(&reader, state, limits, meta, diagnostics);
  if (result != GAUD_OK) {
    failure = result;
    goto Fail;
  }
  state->serial = reader.serial;
  state->audio_offset = reader.page_offset;

  uint64_t granule = 0;
  if (gaud_ogg_last_granule(stream, allocator, state->serial, &granule)
      == GAUD_OK) {
    /*
     * **The pre-skip comes off here and nowhere else.** The granule
     * positions count the samples the encoder's filters needed and the
     * recording does not contain, so the length is the last position
     * minus that number - and a file shorter than its own pre-skip is
     * one whose recording is empty rather than one with a negative
     * length.
     */
    state->frames = granule > state->head.pre_skip
        ? granule - state->head.pre_skip
        : 0;
    state->frames_known = true;
  }
  else {
    note(diagnostics, 0, GAUD_DIAG_WARNING,
        "no page states a granule position, so the length is unknown");
    state->frames_known = false;
  }

  if (state->head.channels > limits->max_channels
      || (state->frames_known && state->frames > limits->max_frames)) {
    failure = GAUD_ERR_LIMIT;
    goto Fail;
  }

  result = gaud_doc_create_internal(codec, stream, allocator, &doc);
  if (result != GAUD_OK) {
    failure = result;
    goto Fail;
  }
  gaud_doc_set_private(doc, state);

  GAUD_Track_Desc desc;
  memset(&desc, 0, sizeof(desc));
  desc.format = GAUD_SAMPLE_S16;
  desc.coding = GAUD_CODING_OPUS;
  /* **48,000 for every Opus file.** The rate in OpusHead is what the
   * encoder was given and the format marks it informational; the
   * granule positions and every decoder's output are at 48 kHz. */
  desc.sample_rate = OPUS_RATE;
  desc.layout = gaud_channel_layout_default(state->head.channels);
  desc.sample_layout = GAUD_LAYOUT_INTERLEAVED;
  desc.frames = state->frames_known ? state->frames : UINT64_MAX;
  desc.data_offset = state->audio_offset;
  desc.data_length = UINT64_MAX;
  desc.codec_private = state;
  result = gaud_doc_add_track(doc, &desc, NULL);
  if (result != GAUD_OK) {
    failure = result;
    goto Fail;
  }

  gaud_meta_verify_pictures(meta);
  gaud_doc_take_meta(doc, meta);
  gaud_ogg_reader_free(&reader);
  *out_doc = doc;
  return GAUD_OK;

Fail:
  gaud_ogg_reader_free(&reader);
  if (doc) {
    gaud_doc_destroy(doc);
  }
  else {
    gcu_allocator_free(allocator, state);
  }
  gaud_meta_destroy(meta);
  return failure;
}

void gaud_opus_close(const GAUD_Codec * codec, GAUD_Doc * doc) {
  (void)codec;
  OPUS_File * state = gaud_doc_private(doc);
  if (!state) {
    return;
  }
  gcu_allocator_free(state->allocator, state);
  gaud_doc_set_private(doc, NULL);
}

/** @brief How many 48 kHz samples the packet at @p data is worth. */
uint32_t gaud_opus_packet_samples(const unsigned char * data, size_t size) {
  return packet_samples(data, size);
}
