/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Audio.
 *
 * Ghoti.io Audio is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Audio is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */


/*
 * GENERATED by tools/tables/gen_opus_tables.py from RFC 6716. Do not edit.
 *
 * Every array here is either extracted from the reference implementation
 * in Appendix A - which section 6 makes normative, and whose archive the
 * RFC publishes a SHA-1 for - or computed from a defining formula and
 * checked against that reference. The generator says which is which, and
 * fails rather than choosing when the two disagree.
 */


/**
 * @file
 *
 * The CELT tables, generated. tools/tables/gen_opus_tables.py says from
 * what, and which of them were checked against a second reading.
 */

#ifndef GHOTI_IO_GAUD_SRC_CODEC_OPUS_OPUS_TABLES_H
#define GHOTI_IO_GAUD_SRC_CODEC_OPUS_OPUS_TABLES_H

#include <ghoti.io/audio/macros.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Band edges in 2.5 ms bins; checked against Table 55. */
extern const int16_t gaud_opus_eband5ms[22];

/** Band widths as log2 in eighths of a bit. */
extern const int16_t gaud_opus_logN400[21];

/** The MDCT overlap window in Q15. */
extern const int16_t gaud_opus_window120[120];

/** Allocation in 1/32 bit per sample, 11 by 21. */
extern const unsigned char gaud_opus_band_allocation[231];

/** Cost of coding one of k+1 values, in eighths of a bit. */
extern const unsigned char gaud_opus_log2_frac_table[24];

/** Time-frequency resolution changes, 4 by 8. */
extern const int8_t gaud_opus_tf_select_table[32];

/** The allocation trim's distribution. */
extern const unsigned char gaud_opus_trim_icdf[11];

/** The spreading decision's distribution. */
extern const unsigned char gaud_opus_spread_icdf[4];

/** The post-filter tap set's distribution. */
extern const unsigned char gaud_opus_tapset_icdf[3];

/** Where each band's pulse cache starts. */
extern const int16_t gaud_opus_cache_index50[105];

/** Bits needed for K pulses in N bins. */
extern const unsigned char gaud_opus_cache_bits50[392];

/** The allocation ceiling per band and channel count. */
extern const unsigned char gaud_opus_cache_caps50[168];

/** Laplace parameters for coarse energy, 4 by 2 by 42. */
extern const unsigned char gaud_opus_e_prob_model[336];

/** The mean energy per band, in Q4 decibels; 21 used of 25. */
extern const int8_t gaud_opus_e_means[25];

/** Coarse energy's time prediction, per frame size, Q15. */
extern const int16_t gaud_opus_pred_coef[4];

/** Coarse energy's frequency prediction, Q15. */
extern const int16_t gaud_opus_beta_coef[4];

/** The same, for a frame coded without history. */
extern const int16_t gaud_opus_beta_intra[1];


#ifdef __cplusplus
}
#endif

#endif // GHOTI_IO_GAUD_SRC_CODEC_OPUS_OPUS_TABLES_H
