/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Audio.
 *
 * Ghoti.io Audio is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Audio is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */


/*
 * GENERATED by tools/tables/gen_opus_tables.py from RFC 6716. Do not edit.
 *
 * Every array here is either extracted from the reference implementation
 * in Appendix A - which section 6 makes normative, and whose archive the
 * RFC publishes a SHA-1 for - or computed from a defining formula and
 * checked against that reference. The generator says which is which, and
 * fails rather than choosing when the two disagree.
 */


/**
 * @file
 *
 * The SILK tables, generated. tools/tables/gen_opus_tables.py says from
 * what, and which of them were checked against a second reading.
 */

#ifndef GHOTI_IO_GAUD_SRC_CODEC_OPUS_OPUS_SILK_TABLES_H
#define GHOTI_IO_GAUD_SRC_CODEC_OPUS_OPUS_SILK_TABLES_H

#include <ghoti.io/audio/macros.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Which of a 40 ms frame's two LBRR frames are coded. */
extern const uint8_t gaud_opus_silk_lbrr_flags_2_icdf[3];

/** The same for 60 ms, over three frames. */
extern const uint8_t gaud_opus_silk_lbrr_flags_3_icdf[7];

/** The stereo weights' shared high-order index. */
extern const uint8_t gaud_opus_silk_stereo_pred_joint_icdf[25];

/** Three equally likely values. */
extern const uint8_t gaud_opus_silk_uniform3_icdf[3];

/** Four equally likely values. */
extern const uint8_t gaud_opus_silk_uniform4_icdf[4];

/** Five equally likely values. */
extern const uint8_t gaud_opus_silk_uniform5_icdf[5];

/** Six equally likely values. */
extern const uint8_t gaud_opus_silk_uniform6_icdf[6];

/** Eight equally likely values. */
extern const uint8_t gaud_opus_silk_uniform8_icdf[8];

/** The sixteen stereo prediction weights, Q13. */
extern const int16_t gaud_opus_silk_stereo_pred_quant_q13[16];

/** Whether the side channel is coded at all. */
extern const uint8_t gaud_opus_silk_stereo_only_code_mid_icdf[2];

/** Frame type in an inactive frame; add 0. */
extern const uint8_t gaud_opus_silk_type_offset_no_vad_icdf[2];

/** Frame type in an active frame; add 2. */
extern const uint8_t gaud_opus_silk_type_offset_vad_icdf[4];

/** The independent gain's top three bits, by signal type. */
extern const uint8_t gaud_opus_silk_gain_icdf[24];

/** A gain coded against the previous subframe's. */
extern const uint8_t gaud_opus_silk_delta_gain_icdf[41];

/** NB and MB stage-1 LSF index, unvoiced then voiced. */
extern const uint8_t gaud_opus_silk_nlsf_cb1_icdf_nb_mb[64];

/** The same for WB. */
extern const uint8_t gaud_opus_silk_nlsf_cb1_icdf_wb[64];

/** NB and MB stage-2 residual, eight distributions of nine. */
extern const uint8_t gaud_opus_silk_nlsf_cb2_icdf_nb_mb[72];

/** The same for WB. */
extern const uint8_t gaud_opus_silk_nlsf_cb2_icdf_wb[72];

/** Per NB/MB coefficient: stage-2 distribution and weight list,
    two per byte. */
extern const uint8_t gaud_opus_silk_nlsf_cb2_select_nb_mb[160];

/** The same for WB. */
extern const uint8_t gaud_opus_silk_nlsf_cb2_select_wb[256];

/** NB and MB backwards prediction weights, two lists of nine, Q8. */
extern const uint8_t gaud_opus_silk_nlsf_pred_nb_mb_q8[18];

/** The same for WB, two lists of fifteen. */
extern const uint8_t gaud_opus_silk_nlsf_pred_wb_q8[30];

/** The NB and MB stage-1 codebook, 32 vectors of 10, Q8. */
extern const uint8_t gaud_opus_silk_nlsf_cb1_nb_mb_q8[320];

/** The WB stage-1 codebook, 32 vectors of 16, Q8. */
extern const uint8_t gaud_opus_silk_nlsf_cb1_wb_q8[512];

/** Minimum spacing between NB and MB LSFs, Q15. */
extern const int16_t gaud_opus_silk_nlsf_delta_min_nb_mb_q15[11];

/** The same for WB. */
extern const int16_t gaud_opus_silk_nlsf_delta_min_wb_q15[17];

/** The extension coded when a stage-2 index saturates. */
extern const uint8_t gaud_opus_silk_nlsf_ext_icdf[7];

/** How far a 20 ms frame interpolates towards the previous LSFs. */
extern const uint8_t gaud_opus_silk_nlsf_interpolation_factor_icdf[5];

/** The order 10 LSFs are evaluated in, which is chosen for accuracy. */
extern const uint8_t gaud_opus_silk_nlsf_ordering10[10];

/** The same for 16. */
extern const uint8_t gaud_opus_silk_nlsf_ordering16[16];

/** Cosine of an LSF, 129 points in Q13 despite the reference's name for it. */
extern const int16_t gaud_opus_silk_lsf_cos_q13[129];

/** The primary pitch lag's high part. */
extern const uint8_t gaud_opus_silk_pitch_lag_icdf[32];

/** A pitch lag coded against the previous frame's. */
extern const uint8_t gaud_opus_silk_pitch_delta_icdf[21];

/** Subframe pitch contour, NB, 10 ms. */
extern const uint8_t gaud_opus_silk_pitch_contour_10_ms_nb_icdf[3];

/** Subframe pitch contour, NB, 20 ms. */
extern const uint8_t gaud_opus_silk_pitch_contour_nb_icdf[11];

/** Subframe pitch contour, MB or WB, 10 ms. */
extern const uint8_t gaud_opus_silk_pitch_contour_10_ms_icdf[12];

/** Subframe pitch contour, MB or WB, 20 ms. */
extern const uint8_t gaud_opus_silk_pitch_contour_icdf[34];

/** The NB 10 ms contour offsets, subframe by subframe. */
extern const int8_t gaud_opus_silk_cb_lags_stage2_10_ms[6];

/** The NB 20 ms contour offsets, subframe by subframe. */
extern const int8_t gaud_opus_silk_cb_lags_stage2[44];

/** The MB and WB 10 ms contour offsets. */
extern const int8_t gaud_opus_silk_cb_lags_stage3_10_ms[24];

/** The MB and WB 20 ms contour offsets. */
extern const int8_t gaud_opus_silk_cb_lags_stage3[136];

/** Which of the three LTP filter codebooks a frame uses. */
extern const uint8_t gaud_opus_silk_ltp_per_index_icdf[3];

/** LTP filter index, periodicity 0. */
extern const uint8_t gaud_opus_silk_ltp_gain_icdf_0[8];

/** LTP filter index, periodicity 1. */
extern const uint8_t gaud_opus_silk_ltp_gain_icdf_1[16];

/** LTP filter index, periodicity 2. */
extern const uint8_t gaud_opus_silk_ltp_gain_icdf_2[32];

/** Eight five-tap LTP filters, Q7. */
extern const int8_t gaud_opus_silk_ltp_gain_vq_0[40];

/** Sixteen five-tap LTP filters, Q7. */
extern const int8_t gaud_opus_silk_ltp_gain_vq_1[80];

/** Thirty-two five-tap LTP filters, Q7. */
extern const int8_t gaud_opus_silk_ltp_gain_vq_2[160];

/** Which LTP scale factor a voiced frame uses. */
extern const uint8_t gaud_opus_silk_ltpscale_icdf[3];

/** The three LTP scale factors, Q14. */
extern const int16_t gaud_opus_silk_ltp_scales_q14[3];

/** The excitation's rate level, by signal type. */
extern const uint8_t gaud_opus_silk_rate_levels_icdf[18];

/** Pulses in a shell block, ten rate levels of eighteen. */
extern const uint8_t gaud_opus_silk_pulses_per_block_icdf[180];

/** Where each pulse count's split distribution starts. */
extern const uint8_t gaud_opus_silk_shell_code_table_offsets[17];

/** Splitting a 16-sample partition. */
extern const uint8_t gaud_opus_silk_shell_code_table3[152];

/** Splitting an 8-sample partition. */
extern const uint8_t gaud_opus_silk_shell_code_table2[152];

/** Splitting a 4-sample partition. */
extern const uint8_t gaud_opus_silk_shell_code_table1[152];

/** Splitting a 2-sample partition. */
extern const uint8_t gaud_opus_silk_shell_code_table0[152];

/** One extra excitation bit. */
extern const uint8_t gaud_opus_silk_lsb_icdf[2];

/** An excitation sign: six contexts by seven pulse counts. */
extern const uint8_t gaud_opus_silk_sign_icdf[42];

/** The excitation's quantization offset, Q10. */
extern const int16_t gaud_opus_silk_quantization_offsets_q10[4];

/** The even output's three all-pass coefficients, Q16. */
extern const int16_t gaud_opus_silk_resampler_up2_hq_0[3];

/** The odd output's three all-pass coefficients, Q16. */
extern const int16_t gaud_opus_silk_resampler_up2_hq_1[3];

/** Twelve polyphase rows of four taps; a row and its mirror make eight, Q15. */
extern const int16_t gaud_opus_silk_resampler_frac_fir_12[48];


#ifdef __cplusplus
}
#endif

#endif // GHOTI_IO_GAUD_SRC_CODEC_OPUS_OPUS_SILK_TABLES_H
