/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Audio.
 *
 * Ghoti.io Audio is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Audio is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file
 *
 * The psychoacoustic model: how much noise each band of a granule may carry
 * before the ear would notice, and whether the granule should be coded as
 * three short blocks.
 *
 * It follows ISO/IEC 11172-3 Annex D's second model in outline - a windowed
 * transform of the signal, a measure of how *predictable* each bin is from
 * the two spectra before it (a predictable bin is a tone, an unpredictable
 * one is noise), energies summed into partitions a third of a Bark wide,
 * masking spread across them, and a threshold below the spread energy that
 * is deeper for tones than for noise - and departs from it where the
 * standard is vague or where the standard's arithmetic is floating point.
 *
 * **It is integer from end to end**, which is the point of the file. The
 * transform is a radix-2 FFT in 32-bit fixed point whose growth is bounded
 * by construction (see `transform`); the unpredictability needs no
 * trigonometry because the phase prediction 2 phi1 - phi2 is a complex
 * multiplication of unit vectors; the tonality index's logarithm and the
 * threshold's power of ten are `mp3enc_math.c`'s table routines; and the
 * spreading function, the Bark scale and the absolute threshold of hearing
 * are tables generated by `tools/tables/gen_mp3enc_psy.py`. Nothing in
 * here can come out differently on another machine.
 *
 * **Units.** A sample of x enters the FFT as (x * window_Q15) >> 10, so a
 * bin's power is 2^10 times that of the plain windowed transform. White
 * noise of variance s^2 has bin power 2^10 * 384 s^2 in the 1024-point
 * transform and 2^10 * 96 s^2 in the 256-point one; the quantiser's unit
 * for the same noise's MDCT line is 56.9 s^2 (long) and 170.7 s^2 (short)
 * - measured, and 16384/288 and 16384/96 on paper - so a threshold of T per
 * bin allows T / 6912 per long line and T / 576 per short one.
 */

#include "mp3enc_internal.h"

/** Bin power to the quantiser's per-line noise units. */
#define LONG_DIVISOR 6912u
#define SHORT_DIVISOR 576u

/** Tonality: the standard's two signal-to-noise extremes, in dB Q8. */
#define SNR_NOISE_Q8 (6 * 256)
#define SNR_TONE_Q8 (18 * 256)

/* ---------------------------------------------------------------- the FFT */

static void fft(int32_t * re, int32_t * im, unsigned n) {
  unsigned bits = 0;
  while ((1u << bits) < n) {
    ++bits;
  }
  for (unsigned i = 0; i < n; ++i) {
    unsigned j = 0;
    for (unsigned b = 0; b < bits; ++b) {
      j |= ((i >> b) & 1u) << (bits - 1u - b);
    }
    if (j > i) {
      int32_t t = re[i];
      re[i] = re[j];
      re[j] = t;
      t = im[i];
      im[i] = im[j];
      im[j] = t;
    }
  }
  for (unsigned len = 2; len <= n; len <<= 1) {
    unsigned half = len >> 1;
    unsigned step = 1024u / len;
    for (unsigned start = 0; start < n; start += len) {
      for (unsigned k = 0; k < half; ++k) {
        int64_t c = gaud_mp3enc_fft_cos[k * step];
        int64_t s = gaud_mp3enc_fft_sin[k * step];
        unsigned a = start + k;
        unsigned b = a + half;
        int32_t tr = (int32_t)((re[b] * c + im[b] * s + (1 << 29)) >> 30);
        int32_t ti = (int32_t)((im[b] * c - re[b] * s + (1 << 29)) >> 30);
        re[b] = re[a] - tr;
        im[b] = im[a] - ti;
        re[a] += tr;
        im[a] += ti;
      }
    }
  }
}

/**
 * Window and transform @p n samples.
 *
 * Bounded without scaling per stage: an input is at most 2^15 * 2^15 / 2^10
 * = 2^20 after the window, a Hann window's coefficients sum to n/2, and a
 * transform's output is at most the sum of its inputs' magnitudes, so the
 * largest value anywhere is 2^20 * 512 = 2^29 and an int32 cannot overflow.
 */
static void transform(const int16_t * pcm, const int16_t * window, unsigned n,
    int32_t * re, int32_t * im) {
  for (unsigned i = 0; i < n; ++i) {
    re[i] = (int32_t)(((int64_t)pcm[i] * window[i] + (1 << 9)) >> 10);
    im[i] = 0;
  }
  fft(re, im, n);
}

/* ----------------------------------------------------------------- rates */

void gaud_mp3e_psy_rate_init(
    MP3E_Psy_Rate * rate, unsigned psy_row, unsigned band_row) {
  memset(rate, 0, sizeof(*rate));
  rate->psy_row = psy_row;
  rate->band_row = band_row;
  rate->long_count = gaud_mp3enc_long_parts[psy_row];
  rate->short_count = gaud_mp3enc_short_parts[psy_row];
  for (unsigned set = 0; set < 2u; ++set) {
    unsigned count = set == 0u ? rate->long_count : rate->short_count;
    const uint16_t * lo = set == 0u ? gaud_mp3enc_long_lo[psy_row] : gaud_mp3enc_short_lo[psy_row];
    const uint16_t * hi = set == 0u ? gaud_mp3enc_long_hi[psy_row] : gaud_mp3enc_short_hi[psy_row];
    const uint16_t * bark = set == 0u ? gaud_mp3enc_long_bark[psy_row] : gaud_mp3enc_short_bark[psy_row];
    for (unsigned j = 0; j < count; ++j) {
      uint32_t norm = 0;
      for (unsigned i = 0; i < count; ++i) {
        int dz_q8 = (int)bark[j] - (int)bark[i];
        /* The masked band j, dz above the masker i; nearest table entry. */
        int index = (dz_q8 * (int)MP3E_SPREAD_STEP + 128 + 256 * (int)MP3E_SPREAD_LOW * (int)MP3E_SPREAD_STEP)
            / 256;
        uint32_t weight = 0;
        if (index >= 0 && index < (int)MP3E_SPREAD_COUNT) {
          weight = gaud_mp3enc_spread[index];
        }
        if (set == 0u) {
          rate->long_spread[i][j] = weight;
        }
        else {
          rate->short_spread[i][j] = weight;
        }
        norm += weight;
      }
      if (set == 0u) {
        rate->long_norm[j] = norm ? norm : 1u;
        rate->long_bins[j] = (uint16_t)(hi[j] - lo[j]);
      }
      else {
        rate->short_norm[j] = norm ? norm : 1u;
        rate->short_bins[j] = (uint16_t)(hi[j] - lo[j]);
      }
    }
    for (unsigned j = 0; j < count; ++j) {
      /* The lines of the MDCT that fall in each partition: line k of the
       * long transform is at (k + 0.5) rate / 1152, which is bin
       * (2k + 1) * 4 / 9 of the 1024-point FFT; line k of a short one is at
       * (k + 0.5) rate / 384, which is bin (2k + 1) / 3 of the 256-point. */
      unsigned lines = set == 0u ? MP3E_LINES : 192u;
      for (unsigned k = 0; k < lines; ++k) {
        unsigned bin = set == 0u ? ((2u * k + 1u) * 4u) / 9u : (2u * k + 1u) / 3u;
        if (bin >= lo[j] && bin < hi[j]) {
          if (set == 0u) {
            rate->long_line_part[k] = (uint8_t)j;
          }
          else {
            rate->short_line_part[k] = (uint8_t)j;
          }
        }
      }
    }
  }
}

void gaud_mp3e_psy_channel_reset(MP3E_Psy_Channel * channel) {
  memset(channel, 0, sizeof(*channel));
}

/* ------------------------------------------------------- unpredictability */

/**
 * How badly bin @p k of the current spectrum is predicted by the two before
 * it, in Q15: 0 for a pure steady tone, 1 for noise.
 *
 * The standard predicts magnitude as 2 r1 - r2 and phase as 2 phi1 - phi2.
 * The predicted *vector* is then r_p times the unit vector u1^2 conj(u2),
 * which needs a complex product and no angle, and the distance from the
 * actual bin over the sum of the magnitudes is the measure.
 */
static uint32_t unpredictability(int32_t re, int32_t im, uint32_t mag,
    const int32_t * re1, const int32_t * im1, const uint32_t * mag1,
    const int32_t * re2, const int32_t * im2, const uint32_t * mag2,
    unsigned k) {
  int64_t u1r = 1 << 30;
  int64_t u1i = 0;
  int64_t u2r = 1 << 30;
  int64_t u2i = 0;
  if (mag1[k]) {
    u1r = ((int64_t)re1[k] << 30) / (int64_t)mag1[k];
    u1i = ((int64_t)im1[k] << 30) / (int64_t)mag1[k];
  }
  if (mag2[k]) {
    u2r = ((int64_t)re2[k] << 30) / (int64_t)mag2[k];
    u2i = ((int64_t)im2[k] << 30) / (int64_t)mag2[k];
  }
  int64_t ar = (u1r * u1r - u1i * u1i) >> 30;
  int64_t ai = (2 * u1r * u1i) >> 30;
  int64_t pr = (ar * u2r + ai * u2i) >> 30;
  int64_t pi = (ai * u2r - ar * u2i) >> 30;
  int64_t rp = 2 * (int64_t)mag1[k] - (int64_t)mag2[k];
  int64_t xr = (rp * pr) >> 30;
  int64_t xi = (rp * pi) >> 30;
  int64_t dr = (int64_t)re - xr;
  int64_t di = (int64_t)im - xi;
  uint64_t distance = gaud_mp3e_isqrt((uint64_t)(dr * dr) + (uint64_t)(di * di));
  uint64_t scale = (uint64_t)mag + (uint64_t)(rp < 0 ? -rp : rp);
  if (scale == 0) {
    return 32768u;
  }
  uint64_t c = (distance << 15) / scale;
  return c > 32768u ? 32768u : (uint32_t)c;
}

/* ---------------------------------------------------------- the thresholds */

/**
 * From a spectrum's bin powers and unpredictabilities to a threshold per
 * partition: the standard's steps 6 to 11 in one place.
 *
 * @param previous The last granule's thresholds, or NULL: a threshold may
 *   not exceed twice its predecessor, which is what stops the model
 *   forgiving a loud onset's noise in the quiet moment before it.
 * @param out_pe Perceptual entropy in bits.
 */
static void thresholds(unsigned count, const uint16_t * lo, const uint16_t * hi,
    const uint64_t * ath, const uint32_t (*spread)[MP3E_MAX_LONG_PARTS],
    const uint32_t * norm, const uint64_t * power, const uint32_t * c15,
    int snr_offset_q8, const uint64_t * previous, uint64_t * out_thr,
    uint32_t * out_pe, size_t spread_stride) {
  uint64_t e[MP3E_MAX_LONG_PARTS];
  uint64_t cw[MP3E_MAX_LONG_PARTS];
  uint64_t max_e = 0;
  for (unsigned p = 0; p < count; ++p) {
    uint64_t sum = 0;
    uint64_t wsum = 0;
    uint64_t high = 0;
    for (unsigned k = lo[p]; k < hi[p]; ++k) {
      sum += power[k];
      high += power[k] >> 16;
      wsum += (power[k] >> 16) * c15[k];
    }
    e[p] = sum;
    uint32_t c_part = high ? (uint32_t)(wsum / high) : 32768u;
    cw[p] = c_part;
    if (sum > max_e) {
      max_e = sum;
    }
  }
  unsigned shift = 0;
  while ((max_e >> shift) > ((uint64_t)1 << 44)) {
    ++shift;
  }
  uint64_t pe_q8 = 0;
  for (unsigned j = 0; j < count; ++j) {
    uint64_t ecb = 0;
    uint64_t ctb = 0;
    for (unsigned i = 0; i < count; ++i) {
      uint32_t s = *((const uint32_t *)((const char *)spread + i * spread_stride) + j);
      uint64_t reduced = e[i] >> shift;
      ecb += reduced * s;
      ctb += ((reduced * cw[i]) >> 15) * s;
    }
    uint32_t cb15 = 32768u;
    if ((ecb >> 15) != 0) {
      uint64_t c = ctb / (ecb >> 15);
      cb15 = c > 32768u ? 32768u : (uint32_t)c;
    }
    if (cb15 == 0) {
      cb15 = 1;
    }
    /* tb = -0.299 - 0.43 ln(cb), in Q15, held to 0..1. */
    int64_t l = (int64_t)gaud_mp3e_log2_q8(cb15) - 15 * 256;
    int64_t tb15 = (-979800 - 3815 * l) / 100;
    if (tb15 < 0) {
      tb15 = 0;
    }
    if (tb15 > 32768) {
      tb15 = 32768;
    }
    int64_t snr_q8 = SNR_NOISE_Q8
        + (((int64_t)(SNR_TONE_Q8 - SNR_NOISE_Q8) * tb15) >> 15) + snr_offset_q8;
    uint32_t bc = gaud_mp3e_exp2_q8((int32_t)(-(snr_q8 * 85) / 256));
    uint64_t en = ecb / norm[j];
    uint64_t nb = ((en * bc) >> 16) << shift;
    uint64_t floor_power = ath[j] * (uint64_t)(hi[j] - lo[j]);
    uint64_t thr = nb;
    if (previous) {
      uint64_t cap = previous[j] > UINT64_MAX / 4u ? UINT64_MAX / 2u : previous[j] * 2u;
      thr = nb < cap ? nb : cap;
    }
    if (thr < floor_power) {
      thr = floor_power;
    }
    out_thr[j] = thr;
    if (e[j] > thr) {
      int32_t diff = gaud_mp3e_log2_q8(e[j]) - gaud_mp3e_log2_q8(thr);
      uint32_t root = gaud_mp3e_exp2_q8(diff / 2);
      int32_t bits_q8 = gaud_mp3e_log2_q8(65536u + (uint64_t)root) - 16 * 256;
      pe_q8 += (uint64_t)(hi[j] - lo[j]) * (uint64_t)bits_q8;
    }
  }
  *out_pe = (uint32_t)(pe_q8 >> 8);
}

/** The noise a band of lines may carry: the partition thresholds summed over
 *  them, per line, in the quantiser's units. */
static uint64_t band_allowed(const uint64_t * thr, const uint16_t * bins,
    const uint8_t * line_part, unsigned from, unsigned to, uint32_t divisor) {
  uint64_t sum = 0;
  for (unsigned k = from; k < to; ++k) {
    unsigned p = line_part[k];
    sum += thr[p] / bins[p] / divisor;
  }
  return sum;
}

void gaud_mp3e_psy_analyze(const MP3E_Psy_Rate * rate,
    MP3E_Psy_Channel * channel, const int16_t * samples, int snr_offset_q8,
    MP3E_Psy_Result * out) {
  memset(out, 0, sizeof(*out));
  /* The newest granule goes on the end of the history. */
  memmove(channel->history, channel->history + MP3E_LINES,
      2u * MP3E_LINES * sizeof(int16_t));
  memcpy(channel->history + 2u * MP3E_LINES, samples,
      MP3E_LINES * sizeof(int16_t));

  /* --- the long spectrum, centred where the long window's MDCT is --- */
  int32_t re[1024];
  int32_t im[1024];
  uint64_t power[513];
  uint32_t c15[513];
  transform(channel->history + 416, gaud_mp3enc_hann_long, 1024, re, im);
  uint32_t mag[513];
  for (unsigned k = 0; k <= 512u; ++k) {
    power[k] = (uint64_t)((int64_t)re[k] * re[k]) + (uint64_t)((int64_t)im[k] * im[k]);
    mag[k] = gaud_mp3e_isqrt(power[k]);
    c15[k] = unpredictability(re[k], im[k], mag[k], channel->long_re[0],
        channel->long_im[0], channel->long_mag[0], channel->long_re[1],
        channel->long_im[1], channel->long_mag[1], k);
  }
  /* Two deep: [0] is the most recent. */
  memcpy(channel->long_re[1], channel->long_re[0], sizeof(channel->long_re[0]));
  memcpy(channel->long_im[1], channel->long_im[0], sizeof(channel->long_im[0]));
  memcpy(channel->long_mag[1], channel->long_mag[0], sizeof(channel->long_mag[0]));
  memcpy(channel->long_re[0], re, 513u * sizeof(int32_t));
  memcpy(channel->long_im[0], im, 513u * sizeof(int32_t));
  memcpy(channel->long_mag[0], mag, sizeof(mag));

  uint64_t long_thr[MP3E_MAX_LONG_PARTS];
  thresholds(rate->long_count, gaud_mp3enc_long_lo[rate->psy_row],
      gaud_mp3enc_long_hi[rate->psy_row], gaud_mp3enc_long_ath[rate->psy_row],
      (const uint32_t (*)[MP3E_MAX_LONG_PARTS])rate->long_spread, rate->long_norm,
      power, c15, snr_offset_q8, channel->long_previous, long_thr,
      &out->pe_long, sizeof(rate->long_spread[0]));
  memcpy(channel->long_previous, long_thr, sizeof(long_thr));

  const uint16_t * bounds = gaud_mp3_sfb_long[rate->band_row];
  for (unsigned b = 0; b < gaud_mp3_sfb_long_bands[rate->band_row]; ++b) {
    out->allowed_long[b] = band_allowed(long_thr, rate->long_bins,
        rate->long_line_part, bounds[b], bounds[b + 1u], LONG_DIVISOR);
  }

  for (unsigned k = 0; k < MP3E_LINES; ++k) {
    unsigned p = rate->long_line_part[k];
    out->allowed_line[k] = long_thr[p] / rate->long_bins[p] / LONG_DIVISOR;
  }

  /* --- three short spectra, at the centres of the three short windows --- */
  for (unsigned w = 0; w < 3u; ++w) {
    transform(channel->history + 608 + 192 * w, gaud_mp3enc_hann_short, 256, re, im);
    uint64_t spower[129];
    uint32_t sc15[129];
    uint32_t smag[129];
    for (unsigned k = 0; k <= 128u; ++k) {
      spower[k] = (uint64_t)((int64_t)re[k] * re[k]) + (uint64_t)((int64_t)im[k] * im[k]);
      smag[k] = gaud_mp3e_isqrt(spower[k]);
      sc15[k] = unpredictability(re[k], im[k], smag[k], channel->short_re[0],
          channel->short_im[0], channel->short_mag[0], channel->short_re[1],
          channel->short_im[1], channel->short_mag[1], k);
    }
    memcpy(channel->short_re[1], channel->short_re[0], sizeof(channel->short_re[0]));
    memcpy(channel->short_im[1], channel->short_im[0], sizeof(channel->short_im[0]));
    memcpy(channel->short_mag[1], channel->short_mag[0], sizeof(channel->short_mag[0]));
    memcpy(channel->short_re[0], re, 129u * sizeof(int32_t));
    memcpy(channel->short_im[0], im, 129u * sizeof(int32_t));
    memcpy(channel->short_mag[0], smag, sizeof(smag));

    uint64_t short_thr[MP3E_MAX_SHORT_PARTS];
    uint32_t pe = 0;
    thresholds(rate->short_count, gaud_mp3enc_short_lo[rate->psy_row],
        gaud_mp3enc_short_hi[rate->psy_row], gaud_mp3enc_short_ath[rate->psy_row],
        (const uint32_t (*)[MP3E_MAX_LONG_PARTS])rate->short_spread, rate->short_norm,
        spower, sc15, snr_offset_q8, NULL, short_thr, &pe,
        sizeof(rate->short_spread[0]));
    out->pe_short += pe;
    const uint16_t * sb = gaud_mp3_sfb_short[rate->band_row];
    for (unsigned b = 0; b < gaud_mp3_sfb_short_bands[rate->band_row]; ++b) {
      out->allowed_short[w][b] = band_allowed(short_thr, rate->short_bins,
          rate->short_line_part, sb[b], sb[b + 1u], SHORT_DIVISOR);
    }
  }

}
