/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Audio.
 *
 * Ghoti.io Audio is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Audio is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file
 *
 * WAV and AIFF: what they read, what they write, and what they refuse.
 *
 * The fixtures these load were generated by ffmpeg and sox, never by this
 * library - see tools/oracle/make_corpus.py. A corpus grown from our own
 * writer agrees with our own reader by construction.
 */

#include <ghoti.io/audio/audio.h>
#include <ghoti.io/audio/codec_sdk.h>
#include <gtest/gtest.h>
#include <math.h>
#include <string.h>
#include <string>
#include <vector>

namespace {

std::string Fixture(const char * name) {
  return std::string(GAUD_TEST_DATA) + "/" + name;
}

struct Loaded {
  GAUD_Stream * stream = nullptr;
  GAUD_Doc * doc = nullptr;
  ~Loaded() {
    gaud_doc_destroy(doc);
    gaud_stream_destroy(stream);
  }
  GAUD_Track * track() { return gaud_doc_track(doc, 0); }
};

bool Open(Loaded & out, const char * name) {
  if (gaud_stream_create_file(Fixture(name).c_str(), &out.stream) != GAUD_OK) {
    return false;
  }
  return gaud_doc_load(nullptr, out.stream, nullptr, nullptr, &out.doc)
      == GAUD_OK;
}

/** Decode a whole track into one vector, a block at a time. */
std::vector<unsigned char> DecodeAll(GAUD_Track * track, size_t block = 97) {
  std::vector<unsigned char> out;
  GAUD_Decoder * decoder = nullptr;
  EXPECT_EQ(gaud_decoder_create(track, &decoder), GAUD_OK);
  GAUD_Buffer * buffer = nullptr;
  EXPECT_EQ(gaud_decoder_buffer_create(decoder, nullptr, block, &buffer),
      GAUD_OK);
  for (;;) {
    EXPECT_EQ(gaud_decoder_read(decoder, buffer), GAUD_OK);
    size_t frames = gaud_buffer_frames(buffer);
    if (frames == 0) {
      break;
    }
    const unsigned char * p
        = static_cast<const unsigned char *>(gaud_buffer_data_const(buffer));
    out.insert(out.end(), p, p + gaud_buffer_bytes_used(buffer));
  }
  gaud_buffer_destroy(buffer);
  gaud_decoder_destroy(decoder);
  return out;
}

class Codecs : public ::testing::Test {
protected:
  void SetUp() override { gaud_register_builtin_codecs(); }
};

} // namespace

TEST_F(Codecs, BothRegisterAndDeclareAnExactEncoder) {
  const GAUD_Codec * wav = gaud_registry_find(nullptr, "wav");
  const GAUD_Codec * aiff = gaud_registry_find(nullptr, "aiff");
  ASSERT_NE(wav, nullptr);
  ASSERT_NE(aiff, nullptr);
  for (const GAUD_Codec * c : {wav, aiff}) {
    EXPECT_TRUE(c->capabilities & GAUD_CAP_DECODE);
    EXPECT_TRUE(c->capabilities & GAUD_CAP_ENCODE);
    // PCM in a chunk: what comes out is determined by what went in.
    EXPECT_EQ(c->encoder_tier, GAUD_ENCODER_EXACT);
    // The phase 1 fields exist, which is what the size gate reports.
    EXPECT_TRUE(gaud_codec_has(c, offsetof(GAUD_Codec, open)));
    EXPECT_TRUE(gaud_codec_has(c, offsetof(GAUD_Codec, encoder_open)));
  }
}

TEST_F(Codecs, RegisteringTwiceIsHarmless) {
  // codecs.h promises this, so a program that does not know how it was
  // linked can simply call the registration functions.
  size_t before = gaud_registry_count(nullptr);
  gaud_register_builtin_codecs();
  gaud_wav_register();
  EXPECT_EQ(gaud_registry_count(nullptr), before);
}

TEST_F(Codecs, WavHeaderIsReadAsTheFileStatesIt) {
  Loaded f;
  ASSERT_TRUE(Open(f, "wav_s16_stereo_44100.wav"));
  EXPECT_STREQ(gaud_doc_codec_name(f.doc), "wav");
  EXPECT_EQ(gaud_doc_track_count(f.doc), 1u);
  EXPECT_EQ(gaud_track_format(f.track()), GAUD_SAMPLE_S16);
  EXPECT_EQ(gaud_track_sample_rate(f.track()), 44100u);
  EXPECT_EQ(gaud_track_channels(f.track()), 2u);
  EXPECT_EQ(gaud_track_frames(f.track()), 4409u);
  EXPECT_NEAR(gaud_track_duration(f.track()), 4409.0 / 44100.0, 1e-9);
}

TEST_F(Codecs, AiffHeaderIsReadAsTheFileStatesIt) {
  Loaded f;
  ASSERT_TRUE(Open(f, "aiff_s16_stereo_44100.aiff"));
  EXPECT_STREQ(gaud_doc_codec_name(f.doc), "aiff");
  EXPECT_EQ(gaud_track_format(f.track()), GAUD_SAMPLE_S16);
  // The rate came through an 80-bit extended float and must land exactly on
  // the integer it was written as.
  EXPECT_EQ(gaud_track_sample_rate(f.track()), 44100u);
  EXPECT_EQ(gaud_track_channels(f.track()), 2u);
  EXPECT_EQ(gaud_track_frames(f.track()), 4409u);
}

TEST_F(Codecs, TheEightBitFormatsDifferBetweenTheTwoContainers) {
  // The disagreement that makes having both codecs in phase 1 worthwhile:
  // WAV's 8-bit is unsigned and AIFF's is signed, and a reader that treated
  // them alike would be wrong by a full-scale DC offset in one of them.
  Loaded w, a;
  ASSERT_TRUE(Open(w, "wav_u8_mono_22050.wav"));
  ASSERT_TRUE(Open(a, "aiff_s8_mono_22050.aiff"));
  EXPECT_EQ(gaud_track_format(w.track()), GAUD_SAMPLE_U8);
  EXPECT_EQ(gaud_track_format(a.track()), GAUD_SAMPLE_S8);
}

TEST_F(Codecs, AifcSowtIsLittleEndianAndStillDecodesToHostOrder) {
  // `sowt` is "twos" backwards: an AIFF whose samples are little-endian.
  // Whatever the container said, the decoded buffer is in host order - that
  // is the whole reason WAV and AIFF can produce the same buffer.
  Loaded sowt, be;
  ASSERT_TRUE(Open(sowt, "aifc_sowt_stereo_44100.aifc"));
  ASSERT_TRUE(Open(be, "aiff_s16_stereo_44100.aiff"));
  EXPECT_EQ(gaud_track_format(sowt.track()), GAUD_SAMPLE_S16);
  // Both must be plausible audio rather than byte-swapped noise, which is
  // what a missed swap sounds and measures like.
  for (Loaded * f : {&sowt, &be}) {
    GAUD_Decoder * d = nullptr;
    ASSERT_EQ(gaud_decoder_create(f->track(), &d), GAUD_OK);
    GAUD_Buffer * b = nullptr;
    ASSERT_EQ(gaud_decoder_buffer_create(d, nullptr, 1000, &b), GAUD_OK);
    ASSERT_EQ(gaud_decoder_read(d, b), GAUD_OK);
    double peak = 0, dc = 0;
    gaud_ops_peak(b, &peak);
    gaud_ops_dc_offset(b, &dc);
    EXPECT_GT(peak, 0.1) << "silent, or swapped into noise";
    EXPECT_LT(peak, 1.01);
    EXPECT_LT(fabs(dc), 0.1) << "a byte-swapped signal has a wild mean";
    gaud_buffer_destroy(b);
    gaud_decoder_destroy(d);
  }
}

TEST_F(Codecs, TheChannelMaskSurvivesAWavWithMoreThanTwoChannels) {
  Loaded f;
  ASSERT_TRUE(Open(f, "wav_s16_5dot1_48000.wav"));
  GAUD_Channel_Layout layout = gaud_track_layout(f.track());
  EXPECT_EQ(layout.channels, 6u);
  if (layout.mask != 0) {
    EXPECT_TRUE(gaud_channel_layout_valid(layout));
    EXPECT_EQ(gaud_channel_layout_at(layout, 3), GAUD_CH_LOW_FREQUENCY)
        << "the LFE moved, which is inaudible to any energy comparison";
  }
}

TEST_F(Codecs, ReadingInBlocksGivesTheSameSamplesAsReadingInOne) {
  // The short read at the end of a track is the path every decode takes and
  // the one a corpus of round numbers never exercises.
  Loaded f;
  ASSERT_TRUE(Open(f, "wav_s24_stereo_48000.wav"));
  std::vector<unsigned char> small = DecodeAll(f.track(), 97);
  std::vector<unsigned char> large = DecodeAll(f.track(), 100000);
  EXPECT_EQ(small, large);
  EXPECT_EQ(small.size(), 2399u * 6u);
}

TEST_F(Codecs, SeekLandsExactlyWhereItWasAsked) {
  // PCM has no inter-frame state, so this is the case out_landed is
  // trivially true for - which is why callers written against it keep
  // working when a codec arrives for which it is not.
  Loaded f;
  ASSERT_TRUE(Open(f, "wav_s16_stereo_44100.wav"));
  GAUD_Decoder * d = nullptr;
  ASSERT_EQ(gaud_decoder_create(f.track(), &d), GAUD_OK);

  uint64_t landed = 12345;
  ASSERT_EQ(gaud_decoder_seek(d, 1000, &landed), GAUD_OK);
  EXPECT_EQ(landed, 1000u);
  EXPECT_EQ(gaud_decoder_tell(d), 1000u);

  GAUD_Buffer * b = nullptr;
  ASSERT_EQ(gaud_decoder_buffer_create(d, nullptr, 10, &b), GAUD_OK);
  ASSERT_EQ(gaud_decoder_read(d, b), GAUD_OK);
  EXPECT_EQ(gaud_buffer_frames(b), 10u);
  EXPECT_EQ(gaud_decoder_tell(d), 1010u);

  // Seeking to the very end is legal and yields nothing.
  ASSERT_EQ(gaud_decoder_seek(d, gaud_track_frames(f.track()), &landed),
      GAUD_OK);
  ASSERT_EQ(gaud_decoder_read(d, b), GAUD_OK);
  EXPECT_EQ(gaud_buffer_frames(b), 0u);

  // Past the end is not.
  EXPECT_EQ(gaud_decoder_seek(d, gaud_track_frames(f.track()) + 1, &landed),
      GAUD_ERR_INVALID);

  gaud_buffer_destroy(b);
  gaud_decoder_destroy(d);
}

TEST_F(Codecs, TwoDecodersOnOneDocumentDoNotStealEachOthersPosition) {
  // They share a stream. A decoder that assumed it was still where it left
  // the stream would read the other's samples, silently - PCM has no
  // framing to disagree with.
  Loaded f;
  ASSERT_TRUE(Open(f, "wav_s16_stereo_44100.wav"));
  GAUD_Decoder * a = nullptr;
  GAUD_Decoder * b = nullptr;
  ASSERT_EQ(gaud_decoder_create(f.track(), &a), GAUD_OK);
  ASSERT_EQ(gaud_decoder_create(f.track(), &b), GAUD_OK);

  GAUD_Buffer * ba = nullptr;
  GAUD_Buffer * bb = nullptr;
  ASSERT_EQ(gaud_decoder_buffer_create(a, nullptr, 16, &ba), GAUD_OK);
  ASSERT_EQ(gaud_decoder_buffer_create(b, nullptr, 16, &bb), GAUD_OK);

  uint64_t landed = 0;
  ASSERT_EQ(gaud_decoder_seek(b, 500, &landed), GAUD_OK);
  ASSERT_EQ(gaud_decoder_read(a, ba), GAUD_OK); // a is still at 0
  ASSERT_EQ(gaud_decoder_read(b, bb), GAUD_OK); // b is at 500
  EXPECT_EQ(gaud_decoder_tell(a), 16u);
  EXPECT_EQ(gaud_decoder_tell(b), 516u);
  EXPECT_NE(memcmp(gaud_buffer_data_const(ba), gaud_buffer_data_const(bb),
                gaud_buffer_bytes_used(ba)),
      0);

  gaud_buffer_destroy(ba);
  gaud_buffer_destroy(bb);
  gaud_decoder_destroy(a);
  gaud_decoder_destroy(b);
}

TEST_F(Codecs, ReadRefusesABufferThatIsTheWrongShape) {
  // Reading converts nothing, which is the same rule load and save follow,
  // so a mismatched buffer is refused rather than quietly adapted.
  Loaded f;
  ASSERT_TRUE(Open(f, "wav_s16_stereo_44100.wav"));
  GAUD_Decoder * d = nullptr;
  ASSERT_EQ(gaud_decoder_create(f.track(), &d), GAUD_OK);

  GAUD_Buffer * wrong_format = nullptr;
  ASSERT_EQ(gaud_buffer_create(nullptr, GAUD_SAMPLE_S32,
                gaud_channel_layout_default(2), GAUD_LAYOUT_INTERLEAVED, 16,
                &wrong_format),
      GAUD_OK);
  EXPECT_EQ(gaud_decoder_read(d, wrong_format), GAUD_ERR_INVALID);

  GAUD_Buffer * wrong_channels = nullptr;
  ASSERT_EQ(gaud_buffer_create(nullptr, GAUD_SAMPLE_S16,
                gaud_channel_layout_default(1), GAUD_LAYOUT_INTERLEAVED, 16,
                &wrong_channels),
      GAUD_OK);
  EXPECT_EQ(gaud_decoder_read(d, wrong_channels), GAUD_ERR_INVALID);

  GAUD_Buffer * wrong_layout = nullptr;
  ASSERT_EQ(gaud_buffer_create(nullptr, GAUD_SAMPLE_S16,
                gaud_channel_layout_default(2), GAUD_LAYOUT_PLANAR, 16,
                &wrong_layout),
      GAUD_OK);
  EXPECT_EQ(gaud_decoder_read(d, wrong_layout), GAUD_ERR_INVALID);

  // A relabelled mask is NOT a shape change and must be accepted.
  GAUD_Buffer * relabelled = nullptr;
  GAUD_Channel_Layout odd = {GAUD_CH_SIDE_LEFT | GAUD_CH_SIDE_RIGHT, 2};
  ASSERT_EQ(gaud_buffer_create(nullptr, GAUD_SAMPLE_S16, odd,
                GAUD_LAYOUT_INTERLEAVED, 16, &relabelled),
      GAUD_OK);
  EXPECT_EQ(gaud_decoder_read(d, relabelled), GAUD_OK);

  gaud_buffer_destroy(wrong_format);
  gaud_buffer_destroy(wrong_channels);
  gaud_buffer_destroy(wrong_layout);
  gaud_buffer_destroy(relabelled);
  gaud_decoder_destroy(d);
}

TEST_F(Codecs, ProbeIdentifiesEveryFixtureFromItsBytes) {
  struct { const char * file; const char * codec; } cases[] = {
      {"wav_s16_stereo_44100.wav", "wav"},
      {"aiff_s16_stereo_44100.aiff", "aiff"},
      {"aifc_sowt_stereo_44100.aifc", "aiff"},
      {"sox_s16_stereo_44100.wav", "wav"},
  };
  for (auto & c : cases) {
    GAUD_Stream * s = nullptr;
    ASSERT_EQ(gaud_stream_create_file(Fixture(c.file).c_str(), &s), GAUD_OK)
        << c.file;
    GAUD_Probe_Result r = {};
    ASSERT_EQ(gaud_probe(nullptr, s, &r), GAUD_OK);
    ASSERT_NE(r.codec_name, nullptr) << c.file;
    EXPECT_STREQ(r.codec_name, c.codec) << c.file;
    EXPECT_EQ(gaud_stream_tell(s), 0u) << "probe moved the stream";
    gaud_stream_destroy(s);
  }
}

TEST_F(Codecs, ARiffThatIsNotAWaveIsNotClaimed) {
  // "RIFF" alone is shared with AVI and several others. Claiming it weakly
  // would give this codec a chance to open a file that is not audio.
  const unsigned char avi[] = {'R', 'I', 'F', 'F', 4, 0, 0, 0, 'A', 'V', 'I',
      ' '};
  GAUD_Stream * s = nullptr;
  ASSERT_EQ(gaud_stream_create_memory(avi, sizeof(avi), &s), GAUD_OK);
  GAUD_Probe_Result r = {};
  ASSERT_EQ(gaud_probe(nullptr, s, &r), GAUD_OK);
  EXPECT_EQ(r.codec_name, nullptr);
  gaud_stream_destroy(s);
}

TEST_F(Codecs, LoadRefusesTruncatedAndNonsenseInput) {
  struct { const char * what; std::vector<unsigned char> bytes; } cases[] = {
      {"empty", {}},
      {"four bytes", {'R', 'I', 'F', 'F'}},
      {"header only", {'R','I','F','F',4,0,0,0,'W','A','V','E'}},
      {"not audio", {'n','o','p','e','!','!','!','!','?','?','?','?'}},
  };
  for (auto & c : cases) {
    GAUD_Stream * s = nullptr;
    ASSERT_EQ(gaud_stream_create_memory(
                  c.bytes.empty() ? nullptr : c.bytes.data(), c.bytes.size(),
                  &s),
        GAUD_OK);
    GAUD_Doc * doc = nullptr;
    GAUD_Result r = gaud_doc_load(nullptr, s, nullptr, nullptr, &doc);
    EXPECT_NE(r, GAUD_OK) << c.what;
    EXPECT_EQ(doc, nullptr) << c.what << ": nothing is written on failure";
    gaud_stream_destroy(s);
  }
}

TEST_F(Codecs, LimitsAreRefusalsRatherThanTruncations) {
  // A limit is a stated promise; exceeding one returns GAUD_ERR_LIMIT and
  // never a truncated answer that parses.
  GAUD_Stream * s = nullptr;
  ASSERT_EQ(gaud_stream_create_file(
                Fixture("wav_s16_5dot1_48000.wav").c_str(), &s),
      GAUD_OK);
  GAUD_Limits limits;
  gaud_limits_default(&limits);
  limits.max_channels = 2;
  GAUD_Doc * doc = nullptr;
  EXPECT_EQ(gaud_doc_load(nullptr, s, &limits, nullptr, &doc),
      GAUD_ERR_LIMIT);
  EXPECT_EQ(doc, nullptr);
  gaud_stream_destroy(s);

  ASSERT_EQ(gaud_stream_create_file(
                Fixture("wav_s16_stereo_44100.wav").c_str(), &s),
      GAUD_OK);
  gaud_limits_default(&limits);
  limits.max_frames = 10;
  EXPECT_EQ(gaud_doc_load(nullptr, s, &limits, nullptr, &doc),
      GAUD_ERR_LIMIT);
  gaud_stream_destroy(s);

  ASSERT_EQ(gaud_stream_create_file(
                Fixture("wav_s16_stereo_44100.wav").c_str(), &s),
      GAUD_OK);
  gaud_limits_default(&limits);
  limits.max_sample_rate = 8000;
  EXPECT_EQ(gaud_doc_load(nullptr, s, &limits, nullptr, &doc),
      GAUD_ERR_LIMIT);
  gaud_stream_destroy(s);
}

TEST_F(Codecs, ATruncatedDataChunkIsReportedAndClamped) {
  // A download that stopped states the length it was going to have. A
  // decoder that believed it would return whatever followed in memory.
  GAUD_Stream * file = nullptr;
  ASSERT_EQ(gaud_stream_create_file(
                Fixture("wav_s16_stereo_44100.wav").c_str(), &file),
      GAUD_OK);
  uint64_t size = 0;
  ASSERT_EQ(gaud_stream_size(file, &size), GAUD_OK);
  std::vector<unsigned char> bytes(static_cast<size_t>(size));
  ASSERT_EQ(gaud_stream_read(file, bytes.data(), bytes.size()), bytes.size());
  gaud_stream_destroy(file);

  bytes.resize(bytes.size() / 2); // cut it in half, header intact
  GAUD_Stream * s = nullptr;
  ASSERT_EQ(gaud_stream_create_memory(bytes.data(), bytes.size(), &s),
      GAUD_OK);
  GAUD_Diagnostics diagnostics = {};
  GAUD_Doc * doc = nullptr;
  ASSERT_EQ(gaud_doc_load(nullptr, s, nullptr, &diagnostics, &doc), GAUD_OK);
  EXPECT_LT(gaud_track_frames(gaud_doc_track(doc, 0)), 4409u);
  EXPECT_GT(diagnostics.count, 0u) << "clamping silently would be worse";
  gaud_diagnostics_destroy(&diagnostics);
  gaud_doc_destroy(doc);
  gaud_stream_destroy(s);
}

TEST_F(Codecs, AnEncoderNeedsASeekableSinkAndSaysSoUpFront) {
  // A RIFF header states a length that is not known until the data has been
  // written, so finish() patches it. Discovering that at finish would mean
  // a caller had already written an hour of audio.
  GAUD_Stream * memory = nullptr;
  ASSERT_EQ(gaud_stream_create_memory_writer(nullptr, &memory), GAUD_OK);
  GAUD_Stream * blind = nullptr;
  ASSERT_EQ(gaud_stream_create_unseekable(memory, &blind), GAUD_OK);

  GAUD_Encode_Params params;
  gaud_encode_params_default(&params);
  GAUD_Encoder * encoder = nullptr;
  EXPECT_EQ(gaud_encoder_create("wav", nullptr, blind, &params, &encoder),
      GAUD_ERR_INVALID)
      << "the wrapper is not writable either, which is caught first";

  gaud_stream_destroy(blind);
  gaud_stream_destroy(memory);
}

TEST_F(Codecs, TheEncoderRefusesAFormatItsContainerCannotSpell) {
  // WAV has no signed 8-bit and AIFF no unsigned 8-bit. Refusing by name
  // beats shifting every sample by 128 unannounced.
  GAUD_Stream * sink = nullptr;
  ASSERT_EQ(gaud_stream_create_memory_writer(nullptr, &sink), GAUD_OK);
  GAUD_Encode_Params params;
  gaud_encode_params_default(&params);
  params.format = GAUD_SAMPLE_S8;
  GAUD_Encoder * encoder = nullptr;
  EXPECT_EQ(gaud_encoder_create("wav", nullptr, sink, &params, &encoder),
      GAUD_ERR_UNSUPPORTED);
  params.format = GAUD_SAMPLE_U8;
  EXPECT_EQ(gaud_encoder_create("aiff", nullptr, sink, &params, &encoder),
      GAUD_ERR_UNSUPPORTED);
  gaud_stream_destroy(sink);
}

TEST_F(Codecs, WritingAfterFinishIsRefused) {
  GAUD_Stream * sink = nullptr;
  ASSERT_EQ(gaud_stream_create_memory_writer(nullptr, &sink), GAUD_OK);
  GAUD_Encode_Params params;
  gaud_encode_params_default(&params);
  GAUD_Encoder * encoder = nullptr;
  ASSERT_EQ(gaud_encoder_create("wav", nullptr, sink, &params, &encoder),
      GAUD_OK);
  GAUD_Buffer * b = nullptr;
  ASSERT_EQ(gaud_buffer_create(nullptr, params.format, params.layout,
                GAUD_LAYOUT_INTERLEAVED, 8, &b),
      GAUD_OK);
  gaud_buffer_set_frames(b, 8);
  ASSERT_EQ(gaud_encoder_write(encoder, b), GAUD_OK);
  ASSERT_EQ(gaud_encoder_finish(encoder), GAUD_OK);
  EXPECT_EQ(gaud_encoder_finish(encoder), GAUD_OK) << "finishing is idempotent";
  EXPECT_EQ(gaud_encoder_write(encoder, b), GAUD_ERR_INVALID)
      << "appending past a header that states the length";
  gaud_buffer_destroy(b);
  gaud_encoder_destroy(encoder);
  gaud_stream_destroy(sink);
}

TEST_F(Codecs, EveryFixtureSurvivesARoundTripThroughBothContainers) {
  // Cross-container is the interesting half: reading big-endian and writing
  // little-endian has to be wrong twice to look right.
  struct { const char * file; const char * to; } cases[] = {
      {"wav_s16_stereo_44100.wav", "aiff"},
      {"aiff_s24_stereo_48000.aiff", "wav"},
      {"wav_f32_stereo_48000.wav", "aiff"},
      {"aifc_sowt_stereo_44100.aifc", "wav"},
      {"wav_s16_5dot1_48000.wav", "wav"},
  };
  for (auto & c : cases) {
    Loaded in;
    ASSERT_TRUE(Open(in, c.file)) << c.file;
    std::vector<unsigned char> original = DecodeAll(in.track());

    GAUD_Encode_Params params;
    gaud_encode_params_default(&params);
    params.format = gaud_track_format(in.track());
    params.sample_rate = gaud_track_sample_rate(in.track());
    params.layout = gaud_track_layout(in.track());

    GAUD_Stream * sink = nullptr;
    ASSERT_EQ(gaud_stream_create_memory_writer(nullptr, &sink), GAUD_OK);
    GAUD_Encoder * encoder = nullptr;
    ASSERT_EQ(gaud_encoder_create(c.to, nullptr, sink, &params, &encoder),
        GAUD_OK)
        << c.file << " -> " << c.to;

    GAUD_Buffer * b = nullptr;
    ASSERT_EQ(gaud_buffer_create(nullptr, params.format, params.layout,
                  GAUD_LAYOUT_INTERLEAVED, original.size()
                      / gaud_frame_size(params.format,
                          params.layout.channels),
                  &b),
        GAUD_OK);
    memcpy(gaud_buffer_data(b), original.data(), original.size());
    gaud_buffer_set_frames(b, gaud_buffer_capacity(b));
    ASSERT_EQ(gaud_encoder_write(encoder, b), GAUD_OK);
    ASSERT_EQ(gaud_encoder_finish(encoder), GAUD_OK);
    EXPECT_EQ(gaud_encoder_frames_written(encoder), gaud_buffer_capacity(b));
    gaud_encoder_destroy(encoder);

    const void * written = nullptr;
    size_t length = 0;
    ASSERT_EQ(gaud_stream_writer_bytes(sink, &written, &length), GAUD_OK);
    GAUD_Stream * back = nullptr;
    ASSERT_EQ(gaud_stream_create_memory(written, length, &back), GAUD_OK);
    GAUD_Doc * doc = nullptr;
    ASSERT_EQ(gaud_doc_load(nullptr, back, nullptr, nullptr, &doc), GAUD_OK)
        << c.file << " -> " << c.to;
    std::vector<unsigned char> again = DecodeAll(gaud_doc_track(doc, 0));
    EXPECT_EQ(original, again) << c.file << " -> " << c.to;

    gaud_buffer_destroy(b);
    gaud_doc_destroy(doc);
    gaud_stream_destroy(back);
    gaud_stream_destroy(sink);
  }
}

TEST_F(Codecs, AnOddSampleCountGetsThePadByteAndStillReadsBack) {
  // RIFF and IFF both pad a chunk to an even length, and the pad byte is
  // counted in one size and not the other. A corpus of round numbers never
  // writes one.
  for (const char * codec : {"wav", "aiff"}) {
    GAUD_Encode_Params params;
    gaud_encode_params_default(&params);
    params.format = GAUD_SAMPLE_S8 ; // one byte per sample
    if (strcmp(codec, "wav") == 0) {
      params.format = GAUD_SAMPLE_U8;
    }
    params.layout = gaud_channel_layout_default(1);

    GAUD_Stream * sink = nullptr;
    ASSERT_EQ(gaud_stream_create_memory_writer(nullptr, &sink), GAUD_OK);
    GAUD_Encoder * encoder = nullptr;
    ASSERT_EQ(gaud_encoder_create(codec, nullptr, sink, &params, &encoder),
        GAUD_OK);
    GAUD_Buffer * b = nullptr;
    ASSERT_EQ(gaud_buffer_create(nullptr, params.format, params.layout,
                  GAUD_LAYOUT_INTERLEAVED, 77, &b),
        GAUD_OK);
    gaud_buffer_set_frames(b, 77); // odd: the data chunk needs a pad byte
    ASSERT_EQ(gaud_encoder_write(encoder, b), GAUD_OK);
    ASSERT_EQ(gaud_encoder_finish(encoder), GAUD_OK);
    gaud_encoder_destroy(encoder);

    const void * written = nullptr;
    size_t length = 0;
    gaud_stream_writer_bytes(sink, &written, &length);
    EXPECT_EQ(length % 2, 0u) << codec << ": the file is not padded to even";

    GAUD_Stream * back = nullptr;
    ASSERT_EQ(gaud_stream_create_memory(written, length, &back), GAUD_OK);
    GAUD_Doc * doc = nullptr;
    ASSERT_EQ(gaud_doc_load(nullptr, back, nullptr, nullptr, &doc), GAUD_OK)
        << codec;
    EXPECT_EQ(gaud_track_frames(gaud_doc_track(doc, 0)), 77u)
        << codec << ": the pad byte was counted as a sample";
    gaud_doc_destroy(doc);
    gaud_stream_destroy(back);
    gaud_buffer_destroy(b);
    gaud_stream_destroy(sink);
  }
}

int main(int argc, char ** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
